name: test and push docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare env
        run: |
          echo OSS_AK=${{ secrets.OSS_AK }} > .env
          echo OSS_SK=${{ secrets.OSS_SK }} >> .env
          echo OSS_BUCKET=${{ secrets.OSS_BUCKET }} >> .env
          echo OSS_REGION=${{ secrets.OSS_REGION }} >> .env
          echo DISABLE_RETRY=1 >> .env
      - run: yarn
      - name: login docker
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u wangsijie --password-stdin
      - name: build
        run: docker build -t wangsijie/static-deploy-tool .
      - name: push
        run: docker push wangsijie/static-deploy-tool
