name: test and push docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
        env:
          OSS_AK: ${{ secrets.OSS_AK }}
          OSS_SK: ${{ secrets.OSS_SK }}
          OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
          OSS_REGION: ${{ secrets.OSS_REGION }}
          DISABLE_RETRY: '1'
      - name: login docker
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u wangsijie --password-stdin
      - name: build
        run: docker build -t wangsijie/static-deploy-tool .
      - name: push
        run: docker push wangsijie/static-deploy-tool
